### ISSUE TITLE
Low transaction fee causing Invalid BTC Transaction

### ISSUE THREAD

**Issue by andymcd33** [bitcoin-wallet/bitcoin-wallet#1081]
Hi there,

Thanks for developing this app, so far I've had a great experience but unfortunately for everyone I'm a bit of a fool so my apologies for raising this here, I just wasn't sure how else to get guidance from the app devs!

I made a BTC transaction using the app and selected economic for the network fee which has resulted in Invalid BTC transaction on the blockchain.

My question is, how do I increase the network fee after submitting the transaction? I'm using version 10.11 however can't find any option to increase the transaction fee to get this to go through. I've seen other people making reference to this but I don't know if this is done in the app or elsewhere.

If someone would be so kind as to take pity on me so I can get this organised it would be greatly appreciated!

**Comment by samfayad** [comment]
you could click on the transaction on the main screen, click on the 3 dots on the bottom right and select raise network fee. The problem is it only provides you with a calculated fee that is generally very high. I wish we could have an option to select the new fee

**Comment by schildbach** [comment]
"Economic fee" is _only_ meant if you don't care about confirmation time, e.g. if you pay to another wallet of yours. In all other cases, keep "normal fee" or select "priority fee".

If you need to raise the fee after the fact, it's going to be really expensive. That's because you need to pay for the original transaction, plus for the "fee raise" transaction you'll be putting on top.

Also, a fee raise isn't always possible due to technical constraints. E.g. if you empty your wallet, there will be nothing left you could pay the raise from. In these cases, the "raise fee" context menu option won't be available.

**Comment by samfayad** [comment]
Could initiating a second transaction with the same amount but a higher fee (normal) replace the initial transaction? aka using the double spending route?

**Comment by schildbach** [comment]
The app uses first-seen-safe transactions, meaning that out of a set of conflicting transactions the first seen by the miner will be mined. So in general, there is no replacement.
