### ISSUE TITLE
Restore wallet: invalid base64 encoding

### ISSUE THREAD

**Issue by lnalex** [bitcoin-wallet/bitcoin-wallet#367]
I reset my phone after having exported my wallet. I want to import it again on my fresh system but I'm surprised by this error: **invalid base64 encoding** and asking to me to retry if it's a bad password. 

I never had this error before and I'm sure my password is correct.

According to [Crypto.java](https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/src/de/schildbach/wallet/util/Crypto.java#L216) it isn't a password problem.

I tried an old backup already restored and the new one created just before this clean up. Both have the problem.

I 🤞  to get back my Bitcoin wallet asap !

**Comment by mattipt** [comment]
I'm having the same problem.

It may be related to some API change as older versions of Bitcoin Wallet are also affected. I tried with the same version that created the backup, 4.41, to no avail. Running Android 7.1.1 on Nexus 5X.

I can confirm that my password is correct and decoding/decrypting the .bin file with openssl as per [Crypto.java](https://github.com/bitcoin-wallet/bitcoin-wallet/blob/bd1d46f3024c59743e067c1848d119974d4dd52f/wallet/src/de/schildbach/wallet/util/Crypto.java#L45-L46) works fine.

**Comment by lnalex** [comment]
I tried so many versions... so desperate. It has to work with older version but doesn't.

**Comment by mattipt** [comment]
Right, I don't know why but it appears that replacing
```
decodeTextAsBytes = BASE64_DECRYPT.decode(textToDecode);
```
with
```
decodeTextAsBytes = android.util.Base64.decode(textToDecode);
```
in Crypto.java allows the wallet to be imported successfully. Sorry, I haven't been able to debug this further.

**Comment by schildbach** [comment]
In order to help, I need to have a look at one of the failing backup files. If you have one for an empty wallet that'll be great. In fact you don't even need to tell the backup password – the base64 decoding happens before decrypting.

**Comment by lnalex** [comment]
@schildbach I don't have empty wallet and cannot create a broken one, for which email I have to send it (with pgp) ?

**Comment by schildbach** [comment]
@lnalex Just report an issue via the app. You can attach files to the generated email.

**Comment by schildbach** [comment]
Ok, I'll merge it. It generally helps if someone tries this first in a real app.

**Comment by schildbach** [comment]
@mattipt Do you think you could send us a report via the app too? Preferably after you tried to restore from the backup so the error message is included in the logfile.

**Comment by mattipt** [comment]
Ok, I've just found the problem, at least for me. I'm happy to report it was _not_ due to a bug in Bitcoin Wallet but a systematically occurring corruption in the backup file. It took me ages to work out as I checked and double checked the original file was just fine. Well, it was until I moved it to a different directory.

I had used Amaze File Manager to copy the wallet backup file from an ownCloud-synchronised directory into /sdcard/Download. Apparently due to a bug in Amaze, the copied file gets padded with lots of zeroes, from about 32kB to exactly 60kB. That's why trim()ing the string before base64 decode worked.

I switched to ES File Explorer and the wallet imported just fine. 

Incidentally, it would be really handy if Bitcoin Wallet could add a file association to automatically open wallet backup files. The current assumption that the backup file is always in Downloads is not always right.

**Comment by lnalex** [comment]
Ok, great. I tried on another device and it is working !

@mattipt I think it is the problem. I use Amaze too with a Seafile-synchronized directory. I tried with another file manager and that's good.

Definitively not a Bitcoin Wallet issue but adding a feature to select a backup in another directory could bypass the problem.

Thanks !

**Comment by schildbach** [comment]
Great to hear you found the problem.

Bitcoin Wallet does add a mime type when archiving a backup, but not all apps keep it. I regularly test GMail and Google Drive. You can restore Bitcoin wallets directly from both apps, so no specific directory is needed in these cases.

**Comment by pasem50** [comment]
@mattipt do you mind sharing the apk you used in importing your backup(after editing the crypto.java file).
I'm also having same issue with a backup from 2015. I have also tried to build the app but have been unsuccessful at that as well.
Thanks in advance.
