### ISSUE TITLE
startup password for app itself

### ISSUE THREAD

**Issue by deathkillz** [bitcoin-wallet/bitcoin-wallet#383]
Having an encrypted wallet is somewhat useless if someone else that gets hold of the phone (eg: phone gets snatched from your hands while screen is unocked) and them can just start the app without any form of authentication and use the app to either export the wallet without password or even directly transfer the entire balance to another address.

maybe this option is burries somewhere deep into the settings but i cant find it.. so my apologies if I overlooked it. In  that case I would suggest putting this on top of the settings list.

thx!

**Comment by schildbach** [comment]
This has been discussed often. Just use the Android lockscreen and encrypt your phone. It has the advantage of protecting all your data, not just your Bitcoins.

**Comment by sup2X** [comment]
The problem is that you need at least 20 characters long password in order to make the encrypted phone resistant to brute-force attacks. Writing long password every time you need to unlock the phone is very annoying. Also, using pin for encryption is like using no encryption at all.

I agree with deathkillz that encrypting the whole wallet (public and private keys) with a key generated from a strong password is the only secure and less annoying solution.
