### ISSUE TITLE
For addresses with UTXOs in blocks before 478559, allow coins to be split

### ISSUE THREAD

**Issue by OzzyBitcoins** [bitcoin-wallet/bitcoin-wallet#418]
Users currently have no indication that most or all of their UTXOs that are controlled by the app are now spendable on two separate chains with different market values.

- Show balance and prices for both BTC and BCC where applicable.

- Allow either manual or automatic 'splitting' of such coins into their own addresses.

OR

- Before or upon sending coins user selects whether to transmit transaction to the BTC network, BCC network or both.

**Comment by schildbach** [comment]
We won't do a multicoin wallet. What you probably want is a separate BCH wallet app.

**Comment by DennisFantoni** [comment]
i cannot get wallet-tool dump to work

./wallet-tool dump --dump-privkey --wallet=./WalletFile --password=SPENDINGPIN >output.txt

to work.  it outputs a text file with a KEYS section, but there is no PRIV and no WIP anywhere in that section. SPENDINGPIN is the spending pin ciphers that successfully sent money from the android app.

if i write a bad SPENDINGPIN the outpit is exactly to the byte the same as if i write the correct SPENDINGPIN.

the keys  in the keys section are like this : 
(when writing the correct SPENDINGPIN)

  DeterministicKey{pub HEX=xxxxxxxxxx, isEncrypted=true, isPubKeyOnly=true}
  addr:xxxxxxxxxxx  hash160:xxxxxxxxxxxx  (M/0H/0/1)

none of the xxxx fields looks like it is a private key

**Comment by DennisFantoni** [comment]
I found a solution. it turns out that wallet-dump will not output the private keys if the backup was made while there was a spending pin set up, even if you specify password=nnnn to the dump command.  solution is to go to the phone and make a new backup after you have disabled spending key, and then decrypt that backup and dump the keys.

when i have sold my 9BCC and gotten some sleep, i will do some more testing and file a useful bug report
