### ISSUE TITLE
Crashing when setting spending PIN

### ISSUE THREAD

**Issue by djanoris** [bitcoin-wallet/bitcoin-wallet#439]
I'm using cyanogenMod 11 (android 4.4.4) without Google Play Services. On LineageOS 13 crashing also results. Device name: Galaxy Nexus (maguro).

**Comment by schildbach** [comment]
Can you attach the logfile and state the time/date of the crash?

Generally, it's more useful if you report the crash via the app. It should offer to send a crash report upon the next app launch.

**Comment by djanoris** [comment]
Support:
" Your phone is running out of memory. We suspect this has something to do
with using a custom cyanogenmod ROM on your Galaxy Nexus. The official
Android 4.3 doesn't have this problem. Also, you're receiving payments
that pay to many wallets at the same time. This uses up memory too.

We suggest not using the spending PIN on your phone "

**Comment by schildbach** [comment]
More specifically, your OS assigns only 64 MB of RAM to the app but doesn't set the "low RAM device" flag.

**Comment by yo6ial** [comment]
Had this issue just now with 7.15.
Old wallet, pin protected. 

java.lang.OutOfMemoryError: Failed to allocate a 1036 byte allocation with 1529632 free bytes and 1493KB until OOM; failed due to fragmentation (required continguous free 131072 bytes for a new buffer where largest contiguous free 106496 bytes)
I even tried to free up ram but to no avail. I guess it's a sandbox limitation. Android 6.0.1, rooted samsung j500f. 

I worked around this by backing up, sendind to another, newer, phone with more ram and newer android (samsung s7), installed the wallet app and restored my wallet in it. Removed the pin and backed up. Restored the backed up copy on my phone.

**Comment by schildbach** [comment]
@yo6ial This is caused by the BouncyCastle implementation of SCrypt using more memory than the native impl we've been using before. It's already fixed in BC, as soon as a new BC is released we'll pick it up.

In the meantime, we reduced the number of SCrypt iterations on non-64-bit devices so that newly set spending PINs don't crash these devices.
