### ISSUE TITLE
Can't use backup to export all private keys.

### ISSUE THREAD

**Issue by Oninous** [bitcoin-wallet/bitcoin-wallet#473]
Started using Bitcoin wallet for android in 2014. I had some backups I made in 2014, 2015, and finally 2017 before transferring the balance to a new phone and wallet. When I use tools to recover the BIP39 from these backup files, I get the private key for only 2 of the address'. There are still 2 address' under "Old Addresses" section which I can't seem to get the private keys for. I'm trying to use the old backups to claim balances of Bitcoin Cash and Bitcoin Gold that those 2 address' have but I can't seem to get the BIP32 or private keys for them. As a side note, I can still access the address' (they now have 0 bitcoin balance) and the wallet/phone they are in.

**Comment by schildbach** [comment]
First of all, Bitcoin Wallet doesn't support BIP39 yet. And if it did, the 12 word seedphrase would only cover the deterministically created addresses (BIP32). And also only those of the keychain you've picked the seed from (there can be inactive keychains in your wallet due to detected vulnerabilities). Nevertheless, all your keys – even the inactive ones – should be in any backup created by v3.47 or later (May 2014). Use [bitcoinj wallet-tool](https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md) to see what's inside backup files.

If you have further problems, please use Options > Report issue or post in the G+ community.
