### ISSUE TITLE
Transaction unconfirmed

### ISSUE THREAD

**Issue by agenfil** [bitcoin-wallet/bitcoin-wallet#488]
Dear sirs 
My transaction efe6c02fa7effb4171b60f87cf502bae750db24e5f7f37e79ed19fcab5d32a0f have been not conformed and now blockchain say it's invalid. Where are my 300usd now? Please advise thanks!!!

**Comment by DavisNT** [comment]
I guess these were transacted with the economic fee (if so, it might take long time to transact). 
Please go to settings and select a different Block explorer (blockexplorer.com seems to "forget" some unconfirmed transactions).

**Comment by lviggiano** [comment]
Transactions gets out of the mempools of the nodes after some time. If they don't get through the miners into the blockchain the funds are returned to their origin with no fee applied. So be patient, and you'll get a refund so you can try again with higher network fees.
Blockexplorer may have a littler mempool than other miners and that's why your unconfirmed transaction isn't listed.

**Comment by agenfil** [comment]
Thanks for your reply.

Ok well noted and will wait until returned back

Il 16 Dic 2017 7:39 PM, "Luigi R. Viggiano" <notifications@github.com> ha
scritto:

**Comment by agenfil** [comment]
Dear Sirs
I am patient but transaction is still in the blockchain in "uncorfirmed"
mode.
When these 0.15 BTC will return back to me?

Il 16 Dic 2017 21:15, "Andreas Schildbach" <notifications@github.com> ha
scritto:

**Comment by schildbach** [comment]
@agenfil This is not a support forum.
