### ISSUE TITLE
How to import wallet privateKey

### ISSUE THREAD

**Issue by 2490037594** [bitcoin-wallet/bitcoin-wallet#561]
I try a number of times to import wallet privateKey,  but it failed, I want import_wallet as the same as. create_wallet,    how to do?

**Comment by schildbach** [comment]
Importing private keys is very dangerous. Therefore, Bitcoin Wallet doesn't support it.

**Comment by schildbach** [comment]
Use standard Bitcoin transactions to move value between wallets.

**Comment by amirziari** [comment]
#561

**Comment by anonymous73** [comment]
Oh I see, so your app will not play along with Paper Wallet. (FDroid). Not even the QR code that paper wallet generates? 

Is this because you are concerned that if another app like Paper Wallet is compromised then someone might have their funds stolen and falsely believe that it could be your app, only because they imported the funds into your app before they were stolen?

**Comment by anonymous73** [comment]
Hi schildbach,

I decided to research this myself after reading the description for Bitcoin Wallet (BW) on F-Droid, in which it states, "Sweeping of Paper Wallets".

So I looked up sweeping and found this useful resource:
https://99bitcoins.com/know-more-private-key-import-vs-sweep-difference/

Basically, "sweeping" and "importing" are two different things.

So if someone does a sweep of a private key via QR, BW will generate a new transaction, spending all the funds of the private key into an existing address on BW?

The article above confirms my above concern about the "relative secrecy" of the previously stored private key (whether a paper wallet, or another app).

My question to you is, do you believe that the average bitcoin user might not realise that after they spend coins from an imported key, that such a key would be useless? Also, is importing a private key problematic in terms of security because now the person would need to keep track of multiple addresses / private keys? Is the problem compounded because there may be no way to recover their funds unless they successfully backup the new private key after each transaction? Ie. Do keys generated via a passphrase system, if that is a factor in how a good wallet private key is generated (HD?), make recovery easier and a person would not be able to generate the passphrase from the private key alone?

**Comment by schildbach** [comment]
@anonymous73 Can you please post questions to the mailing list? Thanks.
