### ISSUE TITLE
Manger

### ISSUE THREAD

**Issue by 831993** [bitcoin-wallet/bitcoin-wallet#592]
Manger

**Comment by kuzayakuza** [comment]
On 17 Jul 2019 3:02 am, "German salas gutierres" <notifications@github.com>
wrote:

Manger

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitcoin-wallet/bitcoin-wallet/issues/592?email_source=notifications&email_token=AKSNVZS6USYC6ITKS7LXS6DP7YLLTA5CNFSM4IEF7QZ2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G7RRG5Q>,
or mute the thread
