### ISSUE TITLE
Update version on fdroid

### ISSUE THREAD

**Issue by eloyesp** [bitcoin-wallet/bitcoin-wallet#607]
I'm trying to help with the f-droid build, but I'm just a beginner on this stuff. I've submitted [this merge-request on fdroiddata](https://gitlab.com/fdroid/fdroiddata/merge_requests/6058) so they can build the last version, but it seems that there is a signatures folder that need to be also updated, and I don't know how to do it.

**Comment by schildbach** [comment]
See my comment there. I'm closing this, because F-Droid is out of our control.

**Comment by squatica** [comment]
The last comment by timestamp in the gitlab discussions is this one https://gitlab.com/fdroid/fdroiddata/issues/1884#note_262017994 from F-Droid's Hans-Christoph Steiner answering your question about logfiles. It seems the ball is in your court now?

**Comment by eloyesp** [comment]
As far as I understand, the last comment explains how to publish the logs, so other F-Droid manteiners can do it, but schildbach is not one, so he still cannot see what is actually happening, so he can not help.

**Comment by squatica** [comment]
Ah, the way I understood it was that f-droid build server already has that feature to publish logs from `fdroid publish`, the two links show the merged requests how it was done (using the `serverwebroot` and `deploy_process_logs` parameters?), so it just needs to be configured in this project, then logs will be available. But I'm not sure, it's pretty confusing. It would be nice to get this issue unstuck, because the wallet in f-droid is now over 3 months old and starts nagging users that "new important security updates" are available, which at this point is false.

**Comment by schildbach** [comment]
As far as I understood the comment, Hans has only given an example for "fdroid build". Someone needs to do a similar thing for "fdroid publish".

If someone has the capacity to dig into this, please do.
