### ISSUE TITLE
How to delete address from address book?

### ISSUE THREAD

**Issue by montvid** [bitcoin-wallet/bitcoin-wallet#621]
I am unable to delete unused addresses from the address book nor set a preferred address for receiving btc. I guess it is a feature request?

**Comment by schildbach** [comment]
Bitcoin Wallet doesn't allow to manually set a receiving address because re-using addresses severely impacts a user's privacy. Rather, the app uses a fresh address for each payment.

Because receiving addresses stay valid for receiving forever, you cannot delete receiving addresses (lefthand column). You can delete sending addresses (righthand column) though.

**Comment by montvid** [comment]
Thanks for the explanation. So if i want to erase the apps transaction, address history I need to reinstall it?

**Comment by schildbach** [comment]
To erase transactions you need to remove your wallet and start a fresh one. You can do that by clearing the app data (in the Android app settings), or un/reinstall the Bitcoin Wallet app.

However if you do that you should make sure you've got a wallet backup and know its backup password. Otherwise you'll loose any remaining coins, and coins that might be sent to the wallet in future.

**Comment by montvid** [comment]
I see but as I read the wallet does an automatic backup on google drive no? I read that there is a automatic backup to the cloud feature but I can not find it? Or should one store the backup oneself manually?
