### ISSUE TITLE
How to restore from old (2013) backup

### ISSUE THREAD

**Issue by captainkazan** [bitcoin-wallet/bitcoin-wallet#647]
It seems back in 2013 when i took backup all I have is a file called  bitcoin-wallet-keys-2013-09-20
this file seems to be different from the current backup files that are generated.
How do I restore from the older format file or am I missing something here.

**Comment by miranda76** [comment]
Duplicate of #

**Comment by schildbach** [comment]
Backup files prefixed with `bitcoin-wallet-keys` can be restored with version up to version v6.35. However, it's recommended to follow the [recovery instructions](https://github.com/bitcoin-wallet/bitcoin-wallet/blob/master/wallet/README.recover.md) instead and sweep that wallet into a freshly created wallet. Some of the private keys in your old wallet might be unsecure due to the [Android RNG security vulnerability](https://bitcoin.org/en/alert/2013-08-11-android) in 2013.

If you've got further user questions, please use Options→Report issue within the app.

**Comment by btc2dogecom** [comment]
> It seems back in 2013 when i took backup all I have is a file called bitcoin-wallet-keys-2013-09-20
> this file seems to be different from the current backup files that are generated.
> How do I restore from the older format file or am I missing something here.

do you get that back? we may help you if you have the backup
www.btc2doge.com
