### ISSUE TITLE
2 addresses added for each request after restoring backup

### ISSUE THREAD

**Issue by jfitie** [bitcoin-wallet/bitcoin-wallet#691]
Requesting a new address using the _Request Payment_ button right after restoring a backup results in 2 addresses added in the address book. So f.ex. doing this 5 times and backing out of each request will result in an address book with 11 addresses in it.
This happens until the app is force closed or the phone rebooted, after that only one address is added for a request. If the app is forced closed right after restoring a backup, this does not happen as well.
This issue is easy to reproduce - just force stop, clear app data, start app, restore backup file, and see for yourself.

**Comment by schildbach** [comment]
Hm, so you hit the request coins button white the replay was still in progress? What if you had waited until finished, would this change the behaviour too?

One thing to note is that the "current address" on the main screen derives addresses too. Would be interesting to check if the additional addresses were maybe "current addresses" rather than "addresses for requesting coins".

Can you upload your logfile from that day? Or use Options→Report issue to report this?

**Comment by MPMokoena** [comment]
Awaiting payment forever.

**Comment by lolly317** [comment]
Hi Bitcoin-Wallet/Bitcoin-Wallet,
I am writing to you in. Regards to an amount of money in. Which I paid
$64.00 Us to receive funds from your company ? Why did I not receive these
funds this is extremely frustrating I hope this is not a scam
Lisa Restall
